Notebook gets specific MARS participant data, puts it into a format a RL model will accept and saves it as npz file named MARS_expert_data. Meant to be run before pretrain_MARS_groundtruth notebook.

In [35]:
import pandas as pd
import numpy as np

In [36]:
%autosave 30

Autosaving every 30 seconds

This is a hardcoded path to the MARS dataset. This CSV file is 1.1GB and contains ~9.7 million lines.

In [37]:
parent_path = "../data/"
data_all = "data_all.csv"
good_labels = "Clarified Proficiency Groups.csv"

In [38]:
df = pd.read_csv(parent_path+data_all)

In [39]:
df

,seconds,trialPhase,currentPosRoll,currentVelRoll,joystickX,peopleName,peopleTrialKey,calculated_vel
0,0.031,1,-15.227051,0.000000,0.000000,1_co_P13,1_co_P13/12_600back_Block3_trial_012.csv,0.000000
1,0.043,1,-15.227051,0.005364,0.000000,1_co_P13,1_co_P13/12_600back_Block3_trial_012.csv,0.000000
2,0.051,1,-15.227051,0.005364,0.000000,1_co_P13,1_co_P13/12_600back_Block3_trial_012.csv,0.000000
3,0.059,1,-15.227051,0.171661,0.000000,1_co_P13,1_co_P13/12_600back_Block3_trial_012.csv,0.000000
4,0.069,1,-15.227051,0.386237,0.000000,1_co_P13,1_co_P13/12_600back_Block3_trial_012.csv,0.000000
...,...,...,...,...,...,...,...,...
9725516,113.298,3,14.955139,-67.162342,0.000000,2_xz_P11,2_xz_P11/04_600back_Block1_trial_004.csv,-44.319846
9725517,113.319,3,13.908691,-64.158275,0.000000,2_xz_P11,2_xz_P11/04_600back_Block1_trial_004.csv,-49.830845
9725518,113.341,3,12.889709,-63.428716,0.000000,2_xz_P11,2_xz_P11/04_600back_Block1_trial_004.csv,-46.317361
9725519,113.363,3,11.785583,-61.197124,-0.000031,2_xz_P11,2_xz_P11/04_600back_Block1_trial_004.csv,-50.187544
9725520,113.384,3,10.664978,-60.639226,-0.000031,2_xz_P11,2_xz_P11/04_600back_Block1_trial_004.csv,-53.362165

In [40]:
df.peopleTrialKey.unique().shape

(1360,)

In [41]:
df.peopleName.unique()

array(['1_co_P13', '2_lp_P4/', '2_mc_P18', '2_rf_P8/', '1_js_P9/',
       '2_at_P19', '2_jm_P23', '2_af_P26', '1_bb_P33', '2_ig_P14',
       '2_es_P22', '2_js_P32', '2_bp_P12', '2_fp_P10', '2_hz_P21',
       '1_al_P29', '1_ec_P34', '1_rf_P8/', '1_lp_P4/', '1_xz_P11',
       '1_ml_P27', '2_js_P9/', '2_nr_P25', '1_xm_P20', '2_fa_P17',
       '2_am_P15', '1_as_P31', '2_de_P30', '1_bd_P16', '2_os_P24',
       '2_sb_P28', '1_es_P22', '2_bb_P33', '1_rl_P3/', '1_ig_P14',
       '1_af_P26', '1_js_P32', '2_rv_P7/', '2_ak_P6/', '1_ms_P2/',
       '2_ss_P1/', '2_co_P13', '1_ir_P5/', '1_jm_P23', '1_at_P19',
       '1_mc_P18', '2_as_P31', '2_rl_P3/', '1_fa_P17', '1_am_P15',
       '1_sb_P28', '1_rv_P7/', '1_os_P24', '1_ak_P6/', '2_bd_P16',
       '1_de_P30', '1_hz_P21', '2_ir_P5/', '2_ec_P34', '2_al_P29',
       '1_ss_P1/', '2_ms_P2/', '1_bp_P12', '1_fp_P10', '2_xm_P20',
       '1_nr_P25', '2_ml_P27', '2_xz_P11'], dtype=object)

In [42]:
df_labels = pd.read_csv(parent_path+good_labels)
df_labels

,ppt_id,Day1 Block1,Day1 Block2,Day1 Block3,Day1 Block 4,Day1 Block5,Day2 Block1,Day2 Block2,Day2 Block3,Day2 Block 4,Day2 Block5
0,ss_P1,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
1,ms_P2,Good,Bad,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Good
2,rl_P3,Good,Good,Good,Good,Good,Medium,Medium,Medium,Good,Good
3,lp_P4,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
4,ir_P5,Medium,Medium,Medium,Medium,Medium,Medium,Bad,Bad,Medium,Bad
5,ak_P6,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
6,rv_P7,Good,Good,Good,Good,Medium,Good,Good,Good,Good,Good
7,rf_P8,Good,Good,Good,Good,Good,Good,Good,Good,Good,Good
8,js_P9,Medium,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad
9,fp_P10,Good,Good,Good,Good,Good,Good,Good,Good,Good,Good
10,xz_P11,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad
11,bp_P12,Good,Medium,Medium,Good,Good,Good,Medium,Medium,Medium,Medium
12,co_P13,Bad,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
13,ig_P14,Medium,Bad,Bad,Medium,Bad,Bad,Bad,Medium,Bad,Medium
14,am_P15,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad
15,bd_P16,Good,Good,Good,Good,Good,Good,Good,Good,Good,Good
16,fa_P17,Medium,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad
17,mc_P18,Medium,Medium,Good,Good,Good,Good,Medium,Good,Good,Good
18,at_P19,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
19,xm_P20,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
20,hz_P21,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Good,Medium
21,es_P22,Bad,Medium,Good,Good,Medium,Medium,Good,Good,Medium,Medium
22,jm_P23,Good,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Bad,Bad
23,os_P24,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
24,nr_P25,Good,Good,Good,Good,Good,Good,Good,Good,Good,Good
25,af_P26,Medium,Good,Good,Good,Good,Good,Good,Good,Good,Good
26,ml_P27,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
27,sb_P28,Medium,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad
28,al_P29,Good,Good,Good,Good,Good,Good,Good,Medium,Medium,Good
29,de_P30,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
30,as_P31,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad
31,js_P32,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium,Medium
32,bb_P33,Medium,Medium,Medium,Good,Medium,Medium,Medium,Medium,Medium,Medium
33,ec_P34,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad,Bad

Here, I get 3 seperate dataframes, one for each participant, using their trial keys. I also filter the dataframes to include only the trial phase in which the participant is in control of the chair.

In [43]:
good_parts = ["1_rf_P8/", "1_fp_P10", "1_bd_P16", "1_nr_P25",
             "2_rf_P8/", "2_fp_P10", "2_bd_P16", "2_nr_P25"]
df = df[df['peopleName'].isin(good_parts)]
df

,seconds,trialPhase,currentPosRoll,currentVelRoll,joystickX,peopleName,peopleTrialKey,calculated_vel
381675,0.035,1,-0.681152,0.000000,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,0.000000
381676,0.043,1,-0.681152,0.032186,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,0.000000
381677,0.056,1,-0.681152,0.230669,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,0.000000
381678,0.066,1,-0.681152,0.445246,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,0.000000
381679,0.077,1,-0.681152,0.659822,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,0.000000
...,...,...,...,...,...,...,...,...
9418906,121.037,3,-8.863220,38.033626,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,35.293579
9418907,121.058,3,-8.195801,37.620567,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,31.781878
9418908,121.077,3,-7.456970,36.236551,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,38.885819
9418909,121.096,3,-6.784058,35.828856,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,35.416453
9418910,121.117,3,-6.102905,34.745247,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,32.435826

In [44]:
df = df[df['trialPhase'] == 3] #filter out reset and crash phases
df

,seconds,trialPhase,currentPosRoll,currentVelRoll,joystickX,peopleName,peopleTrialKey,calculated_vel
381715,0.417,3,-0.277405,0.000000,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,1.373291
381716,0.437,3,-0.252686,0.000000,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,1.235962
381717,0.457,3,-0.225220,-0.514983,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,1.373291
381718,0.477,3,-0.203247,-0.514983,-0.007751,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,1.098633
381719,0.499,3,-0.184021,-0.514983,0.000000,2_rf_P8/,2_rf_P8/12_600back_Block3_trial_012.csv,0.873912
...,...,...,...,...,...,...,...,...
9418906,121.037,3,-8.863220,38.033626,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,35.293579
9418907,121.058,3,-8.195801,37.620567,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,31.781878
9418908,121.077,3,-7.456970,36.236551,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,38.885819
9418909,121.096,3,-6.784058,35.828856,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,35.416453
9418910,121.117,3,-6.102905,34.745247,0.000000,1_nr_P25,1_nr_P25/04_600back_Block1_trial_004.csv,32.435826

In [45]:
df.peopleName.unique().shape

(8,)

In [46]:
df.peopleName.unique()

array(['2_rf_P8/', '2_fp_P10', '1_rf_P8/', '2_nr_P25', '1_bd_P16',
       '2_bd_P16', '1_fp_P10', '1_nr_P25'], dtype=object)

Filtering out unused columns

The \*_simple_df is used to create the input arrays for my models as well as for plotting the original values from the dataset (after I convert to numpy array cause I know how to handle those)

In [47]:
df = df.drop(columns=['peopleTrialKey', 'calculated_vel', 'peopleName'])
df

         seconds  trialPhase  currentPosRoll  currentVelRoll  joystickX
381715     0.417           3       -0.277405        0.000000  -0.007751
381716     0.437           3       -0.252686        0.000000  -0.007751
381717     0.457           3       -0.225220       -0.514983  -0.007751
381718     0.477           3       -0.203247       -0.514983  -0.007751
381719     0.499           3       -0.184021       -0.514983   0.000000
...          ...         ...             ...             ...        ...
9418906  121.037           3       -8.863220       38.033626   0.000000
9418907  121.058           3       -8.195801       37.620567   0.000000
9418908  121.077           3       -7.456970       36.236551   0.000000
9418909  121.096           3       -6.784058       35.828856   0.000000
9418910  121.117           3       -6.102905       34.745247   0.000000

[756945 rows x 5 columns]

Adding a columns of (x,y) coordinates using the position angle and converting my angular velocity from &deg;/sec to rad/sec because that is the observation state the environments accept for input.

In [48]:
#https://sparkbyexamples.com/pandas/pandas-add-column-based-on-another-column/

df = df.assign(x_value=lambda x: np.cos(np.radians(x.currentPosRoll)))
df = df.assign(y_value=lambda y: np.sin(np.radians(y.currentPosRoll)))
df = df.assign(velRads=lambda rad: np.radians(rad.currentVelRoll))
df.iloc[1500:1510, :]

,seconds,trialPhase,currentPosRoll,currentVelRoll,joystickX,x_value,y_value,velRads
383215,32.172,3,3.155823,-0.514983,-0.007751,0.998484,0.055052,-0.008988
383216,32.194,3,3.106384,-0.514983,-0.007751,0.998531,0.054190,-0.008988
383217,32.216,3,3.056946,-0.514983,-0.007751,0.998577,0.053328,-0.008988
383218,32.237,3,3.013000,-0.514983,-0.007751,0.998618,0.052563,-0.008988
383219,32.259,3,2.971802,-0.514983,-0.007751,0.998655,0.051844,-0.008988
383220,32.279,3,2.930603,-0.514983,-0.007751,0.998692,0.051126,-0.008988
383221,32.301,3,2.894897,-0.514983,-0.007751,0.998724,0.050504,-0.008988
383222,32.322,3,2.861938,-0.514983,-0.007751,0.998753,0.049929,-0.008988
383223,32.344,3,2.831726,-0.514983,-0.007751,0.998779,0.049403,-0.008988
383224,32.366,3,2.804260,-0.514983,-0.007751,0.998803,0.048924,-0.008988

In [49]:
print(np.cos(3.155823))
print(np.cos(np.radians(3.155823)))

-0.9998987503291518
0.9984835076784815

In [50]:
df['joystickX'] = df['joystickX'].apply(lambda x: x*-1) #multiply joystick by -1, per dataset instructions
df.iloc[1500:1510, :]

,seconds,trialPhase,currentPosRoll,currentVelRoll,joystickX,x_value,y_value,velRads
383215,32.172,3,3.155823,-0.514983,0.007751,0.998484,0.055052,-0.008988
383216,32.194,3,3.106384,-0.514983,0.007751,0.998531,0.054190,-0.008988
383217,32.216,3,3.056946,-0.514983,0.007751,0.998577,0.053328,-0.008988
383218,32.237,3,3.013000,-0.514983,0.007751,0.998618,0.052563,-0.008988
383219,32.259,3,2.971802,-0.514983,0.007751,0.998655,0.051844,-0.008988
383220,32.279,3,2.930603,-0.514983,0.007751,0.998692,0.051126,-0.008988
383221,32.301,3,2.894897,-0.514983,0.007751,0.998724,0.050504,-0.008988
383222,32.322,3,2.861938,-0.514983,0.007751,0.998753,0.049929,-0.008988
383223,32.344,3,2.831726,-0.514983,0.007751,0.998779,0.049403,-0.008988
383224,32.366,3,2.804260,-0.514983,0.007751,0.998803,0.048924,-0.008988

Converting to numpy arrays because I'm more familar with how to use these than I am with dataframes.

In [51]:
obs_df = df.drop(columns=['seconds', 'trialPhase', 'currentPosRoll', 'joystickX', 'currentVelRoll'])
obs_df

          x_value   y_value   velRads
381715   0.999988 -0.004842  0.000000
381716   0.999990 -0.004410  0.000000
381717   0.999992 -0.003931 -0.008988
381718   0.999994 -0.003547 -0.008988
381719   0.999995 -0.003212 -0.008988
...           ...       ...       ...
9418906  0.988059 -0.154076  0.663812
9418907  0.989787 -0.142556  0.656603
9418908  0.991543 -0.129782  0.632447
9418909  0.992998 -0.118128  0.625332
9418910  0.994333 -0.106314  0.606419

[756945 rows x 3 columns]

In [52]:
# act_df = df['joystickX']
# act_df
act_df = pd.DataFrame().assign(joystick=df['joystickX'])
act_df

         joystick
381715   0.007751
381716   0.007751
381717   0.007751
381718   0.007751
381719  -0.000000
...           ...
9418906 -0.000000
9418907 -0.000000
9418908 -0.000000
9418909 -0.000000
9418910 -0.000000

[756945 rows x 1 columns]

In [53]:
obs_arr = obs_df.to_numpy()
act_arr = act_df.to_numpy()
print(obs_arr.shape)
print(act_arr.shape)

(756945, 3)
(756945, 1)

In [54]:
print(obs_arr[0])
print(act_arr[0])

[ 0.99998828 -0.00484161  0.        ]
[0.007751]

In [55]:
np.savez_compressed(
    "MARS_BC_expert_transitions",
    expert_actions=act_arr,
    expert_observations=obs_arr,
)